### ISSUE TITLE
suggest Using the ArtPlayer Player

### ISSUE THREAD

**Issue by Pantyhose-X** [KhubaibKhan4/Youtube-Clone-KMP#3]
It's very cool!
web Suggested Uses Player https://github.com/zhw2590582/ArtPlayer

A .srt subtitle display in multiple languages

Preview [artplayer.org](https://artplayer.org/)
multiple languages subtitle `https://raw.githubusercontent.com/Pantyhose-X/Pantyhose-X/main/subtitle.srt`

![555](https://github.com/KhubaibKhan4/Youtube-Clone-KMP/assets/42504385/2b0e3d37-94dc-491c-9da2-33550230a45f)

**Comment by KhubaibKhan4** [comment]
Thank you so much for your suggestions. Surely, I will check it out.
